test:
  sessions:
    default:
      database: transitcms_test
      hosts:
        - localhost:27017
      options:
        consistency: :strong
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
        username: travis
        password: travis
  options:
    allow_dynamic_fields: false
    include_root_in_json: false
    include_type_for_serialization: true